#!/bin/bash


USER=${SUDO_USER:-${USER}}

if [ $# -eq 1 ]
then
    if [ $1 = "start" ]
    then
        if [ -f "/opt/download_organizer/download_organizer_startup.service" ]
        then
            mv /opt/download_organizer/download_organizer_startup.service /etc/systemd/system/

            systemctl start download_organizer_startup.service
        fi
        echo "download_organizer running!"
        downloadorganizer
    elif [ $1 = "stop" ]
    then
        killall /usr/bin/python3 2> /dev/null
        if [ -f "/etc/systemd/system/download_organizer_startup.service" ]
        then
            systemctl stop download_organizer_startup.service

            mv /etc/systemd/system/download_organizer_startup.service /opt/download_organizer
        fi
        echo "download_organizer stopped!"
    elif [ $1 = "uninstall" ]
    then
        cd /opt/download_organizer/
        ./uninstall
    else
        echo "Not Valid Option"
    fi
elif [ $# -eq 0 ]
then
    if [[ ! $USER ]];
    then
        USER=`echo $USERNAME`
    fi

    if [[ `id -nu` != $USER ]];
    then
        exit 1
    fi

    python3 /opt/download_organizer/downloadorganizer.py &
else
    echo "Invalid quantity of arguments"
fi
