#!/bin/bash

USER=${SUDO_USER:-${USER}}
INSTALLATION_DIRECTORY="/opt/download_organizer"

echo "Removing the installation directory: $INSTALLATION_DIRECTORY"
if [ -d $INSTALLATION_DIRECTORY ]
then
    rm -r $INSTALLATION_DIRECTORY
    echo "Removed!"
else
    echo "The folder does not exist!"
fi


echo "Deleting the command: downloadorganizer"
if [ -f "/bin/downloadorganizer" ]
then
    rm  "/bin/downloadorganizer"
    echo "Command Deleted!"
else
    echo "The command already don't exists"
fi

echo "Deleting the service /etc/systemd/system/download_organizer_startup.service!"

if [ -f "/etc/systemd/system/download_organizer_startup.service" ]
then
    rm "/etc/systemd/system/download_organizer_startup.service"
    echo "Service Deleted!"
else
    echo "The service doesn't exists"
fi

killall /usr/bin/python3 2> /dev/null

systemctl daemon-reload

echo "downloadorganizer was succefully deleted! :)"